### ISSUE TITLE
창모드 HiDPI 레지스트리 추가 요청

### ISSUE THREAD

**Issue by nanpuhaha** [cr0sh/zandam#1]
창모드로 HiDPI를 적용하는 레지스트리도 백업에 같이 추가해주실 수 있을까요?

**maplestory_window_mode_hidpi.reg**
```reg
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
"C:\\Nexon\\Maple\\GameLauncher.exe"="~ GDIDPISCALING DPIUNAWARE"
"C:\\Nexon\\Maple\\MapleStory.exe"="~ GDIDPISCALING DPIUNAWARE"

```

![2021-10-15 10;20;07 i7-8700](https://user-images.githubusercontent.com/9074297/137417052-f2045b01-6d26-4130-812e-e03adac7fd48.png)

**Comment by cr0sh** [comment]
안녕하세요, 프로젝트에 관심 가져주셔서 감사합니다.
해당 프로젝트는 개발이 중지되어 https://github.com/cr0sh/pc.cro.sh 프로젝트로 이동되었습니다. 그러므로 이슈를 해결하기 어려운 점 양해 부탁드립니다.
